use std::fs;
use chrono::{Local, DateTime};

#[derive(Debug, Clone, PartialEq)]
pub enum TicketType { Bug, Feature, Documentation, Refactor }

#[derive(Debug, Clone)]
pub struct Ticket {
    pub kind: TicketType,
    pub author: String,
    pub title: String,
    pub content: String,
    pub tasks: Vec<String>,
    pub created_at: DateTime<Local>,
}

impl Ticket {
    pub fn new(kind: TicketType, author: &str, title: &str, content: &str, tasks: Vec<String>) -> Self {
        Self {
            kind,
            author: author.to_string(),
            title: title.to_string(),
            content: content.to_string(),
            tasks,
            created_at: Local::now(),
        }
    }

    pub fn render(&self) -> String {
        let mut tasks_rendered = String::new();
        if self.tasks.is_empty() {
            tasks_rendered.push_str("_Aucune tâche définie._");
        } else {
            for task in &self.tasks {
                tasks_rendered.push_str(&format!("- [ ] {}\n", task));
            }
        }

        format!(
            "# {}\nAuthor: @{}\nStatus: Open 🟢\nDate: {}\n\n\
             ## {:?} {}\n\n\
             ### Description\n{}\n\n\
             ### 📋 Tasks\n{}\n\n\
             ---\n*Generated by TicketMaker*",
            self.title.to_uppercase().replace(" ", "_"),
            self.author.to_lowercase(),
            self.created_at.format("%Y-%m-%d %H:%M"),
            self.kind, self.title,
            self.content,
            tasks_rendered
        )
    }

    pub fn save(&self) -> std::io::Result<()> {
        let dir = "tickets";
        let _ = fs::create_dir_all(dir);
        let filename = format!("{}/{}.md", dir, self.title.to_lowercase().replace(" ", "-"));
        fs::write(filename, self.render())
    }
}